services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_latency
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=DeinSicheresPasswort123!
      - DOCKER_INFLUXDB_INIT_ORG=MeineFirma
      - DOCKER_INFLUXDB_INIT_BUCKET=latenzmessung
      - DOCKER_INFLUXDB_INIT_RETENTION_PERIOD=20d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=DeinSuperGeheimerAdminTokenFuerDenPinger

  pinger:
    build:
      context: ./pinger
    container_name: pinger_latency
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=DeinSuperGeheimerAdminTokenFuerDenPinger
      - INFLUXDB_ORG=MeineFirma
      - INFLUXDB_BUCKET=latenzmessung
      - PING_TARGETS=google.de,1.1.1.1,x.com
      - PING_INTERVAL=15

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_latency
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data: