{
 "title": "Latenzmessung",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Glättung 1 Minuten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"latenzmessung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_ms\")\n  |> filter(fn: (r) => r[\"_value\"] != 5000)\n  |> group()\n  |> timedMovingAverage(every: v.windowPeriod, period: 1m)\n  |> yield(name: \"durchschnitt_gerundet_geglättet\")"
    }
   ]
  },
  {
   "title": "Glättung 5 Minuten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"latenzmessung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_ms\")\n  |> filter(fn: (r) => r[\"_value\"] != 5000)\n  |> group()\n  |> timedMovingAverage(every: v.windowPeriod, period: 5m)\n  |> yield(name: \"durchschnitt_gerundet_geglättet\")"
    }
   ]
  },
  {
   "title": "Glättung 30 Minuten",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"latenzmessung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_ms\")\n  |> filter(fn: (r) => r[\"_value\"] != 5000)\n  |> group()\n  |> timedMovingAverage(every: v.windowPeriod, period: 30m)\n  |> yield(name: \"durchschnitt_gerundet_geglättet\")"
    }
   ]
  },
  {
   "title": "Glättung 60 Minuten",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"latenzmessung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_ms\")\n  |> filter(fn: (r) => r[\"_value\"] != 5000)\n  |> group()\n  |> timedMovingAverage(every: v.windowPeriod, period: 60m)\n  |> yield(name: \"durchschnitt_gerundet_geglättet\")"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"latenzmessung\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"response_ms\")\r\n  |> filter(fn: (r) => r[\"_value\"] != 5000)\r\n  |> group(columns: [\"target\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}